/**
 * Constants for use in code NOT in the UI. Displayed statuses should be retrieved at run time
 *
 */

export const ITEM_INVENTORY_STATUSES = {
  AVAILABLE: 'AVAILABLE',
  BACKORDERABLE: 'BACKORDERABLE',
  NOT_ALLOCATED: 'NOT_ALLOCATED',
  BACKORDERED: 'BACKORDERED',
  ALLOCATED: 'ALLOCATED',
  RELEASED: 'RELEASED',
  NETWORK_ALLOCATED: 'NETWORK_ALLOCATED',
};
