export default {
  sections: [
    {
      id: 1000,
      span: 4,
      name: 'LOGO',
      renderTo: 'HEADER',
    },
    {
      id: 1001,
      span: 12,
      name: 'HEADER',
      renderTo: 'HEADER',
    },
    {
      id: 1002,
      name: 'MENU',
      renderTo: 'MENU',
      align: 'LEFT',
    },
    {
      id: 1003,
      span: 16,
      name: 'CONTENT_A',
      renderTo: 'CONTENT',
    },
    {
      id: 1004,
      span: 8,
      name: 'CONTENT_B',
      renderTo: 'CONTENT',
    },
    {
      id: 1005,
      span: 8,
      name: 'CONTENT_C',
      renderTo: 'CONTENT',
    },
    {
      id: 1006,
      span: 16,
      name: 'CONTENT_D',
      renderTo: 'CONTENT',
    },
    {
      id: 1007,
      span: 16,
      name: 'FOOTER',
      renderTo: 'FOOTER',
    },
  ],
  flow: {
    nodes: [
      {
        id: 1001,
        type: 'HEADER',
        text: 'Chapter 2',
        variant: 'h1',
        immediate: true,
        renderTo: 'HEADER',
      },
      {
        id: 1666,
        type: 'BUTTON',
        text: 'Go Back',
        immediate: true,
        renderTo: 'CONTENT_A',
        back: 1001,
        action: 'PREV_CHAPTER',
        prevFlow: 'example',
      },
      {
        id: 1002,
        type: 'BUTTON',
        start: true,
        text: 'I Am a button',
        renderTo: 'CONTENT_A',
        outcomeId: [1003, 1007],
        back: 1666,
        action: 'OUTCOME_ID',
      },
      {
        id: 1003,
        type: 'INTEGER',
        text: 'Thread 1',
        min: 1,
        max: 5,
        renderTo: 'CONTENT_B',
        outcomeId: [1004],
        back: 1002,
        isInput: true,
        required: true,
        inputName: 'flow4Num1',
      },
      {
        id: 1004,
        type: 'INTEGER',
        text: 'Thread 1',
        min: 5,
        max: 10,
        renderTo: 'CONTENT_B',
        outcomeId: [1005, 1006],
        back: 1003,
        isInput: true,
        required: true,
        inputName: 'flow4Num2',
      },
      {
        id: 1005,
        type: 'TEXT',
        text: 'Thread 1',
        label: 'Example Label',
        placeholder: 'Example Placeholder',
        renderTo: 'CONTENT_B',
        back: 1004,
        isInput: true,
        inputName: 'flow4Text1',
      },
      {
        id: 1006,
        type: 'TEXT',
        text: 'Thread 1',
        label: 'Example Label 2',
        placeholder: 'Example Placeholder 2',
        renderTo: 'CONTENT_B',
        back: 1004,
        isInput: true,
        inputName: 'flow4Text2',
      },
      {
        id: 1007,
        type: 'INTEGER',
        text: 'Thread 2',
        required: true,
        min: 1,
        max: 100,
        renderTo: 'CONTENT_C',
        outcomeId: [1008],
        back: 1002,
        action: 'OUTCOME_ID',
        inputName: 'flow4dynamicNum1',
      },
      {
        id: 1008,
        type: 'INTEGER',
        text: 'Thread 2',
        required: true,
        min: 1,
        max: 100,
        renderTo: 'CONTENT_C',
        outcomeId: [1009],
        back: 1007,
        isInput: true,
        inputName: 'flow4dynamicNum2',
      },
      {
        id: 1009,
        type: 'BUTTON',
        text: 'Thread 2',
        renderTo: 'CONTENT_C',
        back: 1008,
        action: 'TRANSITION',
        nextFlow: 'example2',
      },
    ],
  },
  context: {
    flow4Text1: 'default value',
  },
};
