export default {
  flow: {
    nodes: [
      {
        id: 200,
        type: 'BUTTON',
        text: 'I Am a button',
        start: true,
        renderTo: 'CONTENT_D',
        outcomeId: [201],
        action: 'OUTCOME_ID',
      },
      {
        id: 201,
        type: 'TEXT',
        text: 'Thread 1',
        label: 'Example Label',
        placeholder: 'Example Placeholder',
        renderTo: 'CONTENT_D',
        outcomeId: [202],
        back: 200,
        action: 'OUTCOME_ID',
        inputName: 'flow3Text1',
        required: true,
        isInput: true,
      },
      {
        id: 202,
        type: 'INTEGER',
        text: 'Thread 1',
        min: 1,
        max: 10,
        renderTo: 'CONTENT_D',
        outcomeId: [203],
        back: 201,
        inputName: 'flow3Number1',
        required: true,
        isInput: true,
      },
      {
        id: 203,
        type: 'BUTTON',
        text: 'Submit',
        renderTo: 'CONTENT_H',
        back: 202,
        action: 'NEXT_CHAPTER',
        nextFlow: 'example4',
      },
    ],
  },
  context: {},
};
