export default {
  sections: [
    {
      id: 2,
      span: 12,
      name: 'HEADER',
      renderTo: 'HEADER',
      margin: 1,
      padding: 1,
      background: 'white',
    },
    {
      id: 1,
      span: 4,
      name: 'LOGO',
      renderTo: 'HEADER',
    },
    {
      id: 4,
      name: 'MENU',
      renderTo: 'MENU',
      align: 'RIGHT',
    },
    {
      id: 3,
      span: 16,
      name: 'CONTENT_A',
      renderTo: 'CONTENT',
      margin: 1,
      padding: 1,
    },
    {
      id: 4,
      span: 8,
      name: 'CONTENT_B',
      renderTo: 'CONTENT',
      margin: 1,
      padding: 1,
    },
    {
      id: 5,
      span: 8,
      name: 'CONTENT_C',
      renderTo: 'CONTENT',
      margin: 1,
      padding: 1,
    },
    {
      id: 6,
      span: 16,
      name: 'CONTENT_D',
      renderTo: 'CONTENT',
      margin: 1,
      padding: 1,
    },
    {
      id: 7,
      span: 4,
      name: 'CONTENT_E',
      renderTo: 'CONTENT',
      margin: 1,
      padding: 1,
    },
    {
      id: 8,
      span: 4,
      name: 'CONTENT_F',
      renderTo: 'CONTENT',
      margin: 1,
      padding: 1,
    },
    {
      id: 9,
      span: 4,
      name: 'CONTENT_G',
      renderTo: 'CONTENT',
      margin: 1,
      padding: 1,
    },
    {
      id: 10,
      span: 4,
      name: 'CONTENT_H',
      renderTo: 'CONTENT',
      margin: 1,
      padding: 1,
    },
    {
      id: 11,
      span: 16,
      name: 'FOOTER',
      renderTo: 'FOOTER',
      margin: 1,
      padding: 1,
    },
  ],
  flow: {
    nodes: [
      {
        id: 900,
        type: 'IMAGE',
        src: 'felix.png',
        immediate: true,
        renderTo: 'LOGO',
        width: '100px',
        height: '100px',
      },
      {
        id: 901,
        type: 'HEADER',
        text: 'Chapter 1',
        variant: 'h1',
        immediate: true,
        renderTo: 'HEADER',
      },
      {
        id: 902,
        type: 'CUSTOMLIST',
        start: true,
        renderTo: 'MENU',
        back: 901,
        action: 'OUTCOME_ID',
        isInput: true,
        required: true,
        inputName: 'customlist',
        options: [
          {
            id: 901,
            label: 'Product A',
            value: 1,
            action: 'TRANSITION',
            nextFlow: 'example1',
          },
          {
            id: 902,
            label: 'Product B',
            value: 2,
            action: 'TRANSITION',
            nextFlow: 'example1',
          },
          {
            id: 903,
            label: 'Product C',
            value: 3,
            action: 'TRANSITION',
            nextFlow: 'example1',
          },
          {
            id: 904,
            label: 'Product D',
            value: 4,
            action: 'TRANSITION',
            nextFlow: 'example1',
          },
          {
            id: 905,
            label: 'Product E',
            value: 5,
            action: 'TRANSITION',
            nextFlow: 'example1',
          },
          {
            id: 906,
            label: 'Product F',
            value: 6,
            action: 'TRANSITION',
            nextFlow: 'example1',
          },
          {
            id: 907,
            label: 'Product G',
            value: 7,
            action: 'TRANSITION',
            nextFlow: 'example1',
          },
          {
            id: 908,
            label: 'Product H',
            value: 8,
            action: 'TRANSITION',
            nextFlow: 'example1',
          },
        ],
      },
    ],
  },
  context: {},
};
