export default {
  flow: {
    nodes: [
      {
        id: 100,
        type: 'BUTTON',
        text: 'I Am a button',
        start: true,
        renderTo: 'CONTENT_D',
        outcomeId: [101, 102],
        back: 1,
        action: 'OUTCOME_ID',
      },
      {
        id: 101,
        type: 'TEXT',
        text: 'Thread 1',
        label: 'Example Label',
        placeholder: 'Example Placeholder',
        renderTo: 'CONTENT_D',
        back: 100,
        action: 'OUTCOME_ID',
        isInput: true,
        inputName: 'flow2Text1',
        required: true,
      },
      {
        id: 102,
        type: 'INTEGER',
        text: 'Thread 1',
        min: 1,
        max: 10,
        renderTo: 'CONTENT_D',
        outcomeId: [103],
        back: 100,
        isInput: true,
        inputName: 'flow2Number1',
        required: true,
      },
      {
        id: 103,
        type: 'BUTTON',
        text: 'Flow 3',
        renderTo: 'CONTENT_D',
        back: 102,
        action: 'TRANSITION',
        nextFlow: 'example3',
      },
    ],
  },
  context: {
    flow2Text1: 'lorem ipsum',
    flow2Number1: 5,
  },
};
