export const blocks = {
  ORDER_TOTAL_CHANGED: 'Order Total Changed',
  INV_CHECK_FAILED: 'Invalid Check Failed',
  ADDRESS_VALIDATION_FAILED: 'Address Validation Failed',
  RESERVEPAYMENT_FAILED: 'Reserve Payment Failed',
  RELEASE_CANCELED: 'Release Canceled',
  WALKTHROUGH_REQUESTED: 'Walkthrough Requested',
  CANCELLATION_PENDING: 'Cancellation Pending',
  INVALID_SHIP_TO_ADDRESS: 'Invalid Ship to Address',
  FRAUDCHECK_FAILED: 'Fraudcheck Failed',
  AVS_MISMATCH: 'AVS Mismatch',
  MULTIPLE_ORDERS: 'Multiple Orders',
  PROMO_FRAUD: 'Promo Fraud',
  ADDRESS_BYPASS: 'Address Bypass',
  VET_DIET_OVERFLOW: 'Vet Diet Overflow',
  RX_REQUIRED: 'RX Required',
  RESTRICTED_AVAILABILITY: 'Restricted Availability',
  OTHER: 'Other',
};
